[package]
name = "cyphernet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "4.0.0-beta.4"
socks = "0.3.4"
multibase = { version = "0.9.1" }
secp256k1 = { version = "0.25.0", optional = true }
ed25519 = { package = "ed25519-compact", version = "2.0.2", features = ["ed25519", "x25519"], optional = true }
chacha20poly1305 = "0.10.1"
hmac = "0.12.1"
sha2 = "0.10.6"
sha3 = { version = "0.10.6", optional = true }
base32 = { version = "0.4.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
quickcheck_macros = { version = "1", default-features = false }
quickcheck = { version = "1", default-features = false }

[features]
default = []
all = ["serde", "tor", "i2p", "nym", "dns", "pem", "ed25519", "secp256k1", "rand", "keygen"]
tor = ["sha3", "ed25519", "base32"]
i2p = ["ed25519"]
nym = []
dns = []
pem = ["ed25519/pem"]
keygen = ["rand", "secp256k1/rand", "ed25519/random"]
