[package]
name = "cyphernet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify_derive = "2.11.2"
socks = "0.3.4"
data-encoding = "2.3.2"
torut = { version = "0.2.1", optional = true }
secp256k1 = { version = "0.24.0", optional = true }
ed25519 = { package = "ed25519-compact", version = "1.0.16", optional = true }

[features]
default = []
tor = ["torut"]
i2p = ["ed25519"]
nym = []
dns = []
