[workspace]
members = [".", "noise_xk"]

[package]
name = "cyphernet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amplify = "4.0.0-beta.4"
socks = "0.3.4"
multibase = { version = "0.9.1" }
# TODO: Remove torut dep
torut = { version = "0.2.1", optional = true }
secp256k1 = { version = "0.25.0", optional = true }
ed25519 = { package = "ed25519-compact", version = "2.0.2", features = ["ed25519", "x25519"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
quickcheck_macros = { version = "1", default-features = false }
quickcheck = { version = "1", default-features = false }

[features]
default = []
all = ["serde", "tor", "i2p", "nym", "dns", "pem", "ed25519", "secp256k1", "rand"]
tor = ["torut"]
i2p = ["ed25519"]
nym = []
dns = []
pem = ["ed25519/pem"]
